export const TICHER = [
    {
      id: "1",
      title: "Урок 1",
      discription1: "Вопросы",
      discription2: "Местоимения",
      discription3: "Таможня",
      data: {
        word: {
          Глаголы: [
            {
              word: "урок1/глаголы/Слово1",
              phrase: "урок1/глаголыСлово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/глаголы/Слово2",
              phrase: "урок1/глаголыСлово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/глаголы/Слово3",
              phrase: "урок1/глаголыСлово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/глаголы/Слово4",
              phrase: "урок1/глаголыСлово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/глаголы/Слово5",
              phrase: "урок1/глаголы/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
          Существительные: [
            {
              word: "урок1/Существительные/Слово1",
              phrase: "урок1/Существительные/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/Существительные/Слово2",
              phrase: "урок1/Существительные/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/глаголы/Слово3",
              phrase: "урок1/глаголыСлово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/глаголы/Слово4",
              phrase: "урок1/глаголыСлово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/глаголы/Слово5",
              phrase: "урок1/глаголы/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
  
          Вопросы: [
            {
              word: "урок1/Вопросы/Слово1",
              phrase: "урок1/Вопросы/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/Вопросы/Слово2",
              phrase: "урок1/Вопросы/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/Вопросы/Слово3",
              phrase: "урок1/Вопросы/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/Вопросы/Слово4",
              phrase: "урок1/Вопросы/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/Вопросы/Слово5",
              phrase: "урок1/Вопросы/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
        },
        phrase: {
          "Тема фраз1": [
            {
              word: "урок1/Тема фраз1/Слово1",
              phrase: "урок1/Тема фраз1/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/Тема фраз1/Слово2",
              phrase: "урок1/Тема фраз1/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/Тема фраз1/Слово3",
              phrase: "урок1/Тема фраз1/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/Тема фраз1/Слово4",
              phrase: "урок1/Тема фраз1/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/Тема фраз1/Слово5",
              phrase: "урок1/Тема фраз1/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
          "Тема фраз2": [
            {
              word: "урок1/Тема фраз2/Слово1",
              phrase: "урок1/Тема фраз2/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/Тема фраз2/Слово2",
              phrase: "урок1/Тема фраз2/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/Тема фраз2/Слово3",
              phrase: "урок1/Тема фраз2/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/Тема фраз2/Слово4",
              phrase: "урок1/Тема фраз2/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/Тема фраз2/Слово5",
              phrase: "урок1/Тема фраз2/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
  
          "Тема фраз3": [
            {
              word: "урок1/Тема фраз3/Слово1",
              phrase: "урок1/Тема фраз3/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/Тема фраз3/Слово2",
              phrase: "урок1/Тема фраз3/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/Тема фраз3/Слово3",
              phrase: "урок1/Тема фраз3/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/Тема фраз3/Слово4",
              phrase: "урок1/Тема фраз3/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок1/Тема фраз3/Слово5",
              phrase: "урок1/Тема фраз3/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
        },
      },
    },
    {
      id: "2",
      title: "Урок 2",
      discription1: "Работа2",
      discription2: "Движуха2",
      discription3: "Транспорт2",
      discription4: "Спорт2",
      data: {
        word: {
          Глаголы: [
            {
              word: "урок2/глаголы/Слово",
              phrase: "урок2/глаголыСлово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/глаголы/Слово2",
              phrase: "урок2/глаголыСлово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/глаголы/Слово3",
              phrase: "урок2/глаголыСлово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/глаголы/Слово4",
              phrase: "урок2/глаголыСлово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/глаголы/Слово5",
              phrase: "урок2/глаголы/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
          Существительные: [
            {
              word: "урок2/Существительные/Слово1",
              phrase: "урок2/Существительные/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/Существительные/Слово2",
              phrase: "урок2/Существительные/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/глаголы/Слово3",
              phrase: "урок2/глаголыСлово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/глаголы/Слово4",
              phrase: "урок2/глаголыСлово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/глаголы/Слово5",
              phrase: "урок2/глаголы/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
  
          Вопросы: [
            {
              word: "урок2/Вопросы/Слово1",
              phrase: "урок2/Вопросы/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/Вопросы/Слово2",
              phrase: "урок2/Вопросы/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/Вопросы/Слово3",
              phrase: "урок2/Вопросы/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/Вопросы/Слово4",
              phrase: "урок2/Вопросы/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/Вопросы/Слово5",
              phrase: "урок2/Вопросы/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
        },
        phrase: {
          "Тема фраз1": [
            {
              word: "урок2/Тема фраз1/Слово1",
              phrase: "урок2/Тема фраз1/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/Тема фраз1/Слово2",
              phrase: "урок2/Тема фраз1/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/Тема фраз1/Слово3",
              phrase: "урок2/Тема фраз1/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/Тема фраз1/Слово4",
              phrase: "урок2/Тема фраз1/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/Тема фраз1/Слово5",
              phrase: "урок2/Тема фраз1/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
          "Тема фраз2": [
            {
              word: "урок2/Тема фраз2/Слово1",
              phrase: "урок2/Тема фраз2/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/Тема фраз2/Слово2",
              phrase: "урок2/Тема фраз2/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/Тема фраз2/Слово3",
              phrase: "урок2/Тема фраз2/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/Тема фраз2/Слово4",
              phrase: "урок2/Тема фраз2/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/Тема фраз2/Слово5",
              phrase: "урок2/Тема фраз2/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
  
          "Тема фраз3": [
            {
              word: "урок2/Тема фраз3/Слово1",
              phrase: "урок2/Тема фраз3/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/Тема фраз3/Слово2",
              phrase: "урок2/Тема фраз3/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/Тема фраз3/Слово3",
              phrase: "урок2/Тема фраз3/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/Тема фраз3/Слово4",
              phrase: "урок2/Тема фраз3/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок2/Тема фраз3/Слово5",
              phrase: "урок2/Тема фраз3/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
        },
      },
    },
    {
      id: "3",
      title: "Урок 3",
      discription1: "Работа3",
      discription2: "Движуха3",
      discription3: "Транспорт3",
      discription4: "Спорт3",
      data: {
        word: {
          Глаголы: [
            {
              word: "урок3/глаголы/Слово",
              phrase: "урок3/глаголыСлово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/глаголы/Слово2",
              phrase: "урок3/глаголыСлово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/глаголы/Слово3",
              phrase: "урок3/глаголыСлово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/глаголы/Слово4",
              phrase: "урок3/глаголыСлово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/глаголы/Слово5",
              phrase: "урок3/глаголы/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
          Существительные: [
            {
              word: "урок3/Существительные/Слово1",
              phrase: "урок3/Существительные/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/Существительные/Слово2",
              phrase: "урок3/Существительные/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/глаголы/Слово3",
              phrase: "урок3/глаголыСлово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/глаголы/Слово4",
              phrase: "урок3/глаголыСлово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/глаголы/Слово5",
              phrase: "урок3/глаголы/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
  
          Вопросы: [
            {
              word: "урок3/Вопросы/Слово1",
              phrase: "урок3/Вопросы/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/Вопросы/Слово2",
              phrase: "урок3/Вопросы/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/Вопросы/Слово3",
              phrase: "урок3/Вопросы/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/Вопросы/Слово4",
              phrase: "урок3/Вопросы/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/Вопросы/Слово5",
              phrase: "урок3/Вопросы/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
        },
        phrase: {
          "Тема фраз1": [
            {
              word: "урок3/Тема фраз1/Слово1",
              phrase: "урок3/Тема фраз1/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/Тема фраз1/Слово2",
              phrase: "урок3/Тема фраз1/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/Тема фраз1/Слово3",
              phrase: "урок3/Тема фраз1/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/Тема фраз1/Слово4",
              phrase: "урок3/Тема фраз1/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/Тема фраз1/Слово5",
              phrase: "урок3/Тема фраз1/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
          "Тема фраз2": [
            {
              word: "урок3/Тема фраз2/Слово1",
              phrase: "урок3/Тема фраз2/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/Тема фраз2/Слово2",
              phrase: "урок3/Тема фраз2/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/Тема фраз2/Слово3",
              phrase: "урок3/Тема фраз2/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/Тема фраз2/Слово4",
              phrase: "урок3/Тема фраз2/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/Тема фраз2/Слово5",
              phrase: "урок3/Тема фраз2/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
  
          "Тема фраз3": [
            {
              word: "урок3/Тема фраз3/Слово1",
              phrase: "урок3/Тема фраз3/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/Тема фраз3/Слово2",
              phrase: "урок3/Тема фраз3/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/Тема фраз3/Слово3",
              phrase: "урок3/Тема фраз3/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/Тема фраз3/Слово4",
              phrase: "урок3/Тема фраз3/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок3/Тема фраз3/Слово5",
              phrase: "урок3/Тема фраз3/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
        },
      },
    },
    {
      id: "4",
      title: "Урок 4",
      discription1: "Работа4",
      discription2: "Движуха4",
      discription3: "Транспорт4",
      discription4: "Спорт4",
      data: {
        word: {
          Глаголы: [
            {
              word: "урок4/глаголы/Слово",
              phrase: "урок4/глаголыСлово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/глаголы/Слово2",
              phrase: "урок4/глаголыСлово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/глаголы/Слово3",
              phrase: "урок4/глаголыСлово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/глаголы/Слово4",
              phrase: "урок4/глаголыСлово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/глаголы/Слово5",
              phrase: "урок4/глаголы/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
          Существительные: [
            {
              word: "урок4/Существительные/Слово1",
              phrase: "урок4/Существительные/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/Существительные/Слово2",
              phrase: "урок4/Существительные/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/глаголы/Слово3",
              phrase: "урок4/глаголыСлово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/глаголы/Слово4",
              phrase: "урок4/глаголыСлово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/глаголы/Слово5",
              phrase: "урок4/глаголы/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
  
          Вопросы: [
            {
              word: "урок4/Вопросы/Слово1",
              phrase: "урок4/Вопросы/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/Вопросы/Слово2",
              phrase: "урок4/Вопросы/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/Вопросы/Слово3",
              phrase: "урок4/Вопросы/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/Вопросы/Слово4",
              phrase: "урок4/Вопросы/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/Вопросы/Слово5",
              phrase: "урок4/Вопросы/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
        },
        phrase: {
          "Тема фраз1": [
            {
              word: "урок4/Тема фраз1/Слово1",
              phrase: "урок4/Тема фраз1/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/Тема фраз1/Слово2",
              phrase: "урок4/Тема фраз1/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/Тема фраз1/Слово3",
              phrase: "урок4/Тема фраз1/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/Тема фраз1/Слово4",
              phrase: "урок4/Тема фраз1/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/Тема фраз1/Слово5",
              phrase: "урок4/Тема фраз1/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
          "Тема фраз2": [
            {
              word: "урок4/Тема фраз2/Слово1",
              phrase: "урок4/Тема фраз2/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/Тема фраз2/Слово2",
              phrase: "урок4/Тема фраз2/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/Тема фраз2/Слово3",
              phrase: "урок4/Тема фраз2/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/Тема фраз2/Слово4",
              phrase: "урок4/Тема фраз2/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/Тема фраз2/Слово5",
              phrase: "урок4/Тема фраз2/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
  
          "Тема фраз3": [
            {
              word: "урок4/Тема фраз3/Слово1",
              phrase: "урок4/Тема фраз3/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/Тема фраз3/Слово2",
              phrase: "урок4/Тема фраз3/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/Тема фраз3/Слово3",
              phrase: "урок4/Тема фраз3/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/Тема фраз3/Слово4",
              phrase: "урок4/Тема фраз3/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок4/Тема фраз3/Слово5",
              phrase: "урок4/Тема фраз3/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
        },
      },
    },
    {
      id: "5",
      title: "Урок 5",
      discription1: "Работа5",
      discription2: "Движуха5",
      discription3: "Транспорт5",
      discription4: "Спорт5",
      data: {
        word: {
          Глаголы: [
            {
              word: "урок5/глаголы/Слово",
              phrase: "урок4/глаголыСлово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/глаголы/Слово2",
              phrase: "урок4/глаголыСлово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/глаголы/Слово3",
              phrase: "урок5/глаголыСлово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/глаголы/Слово4",
              phrase: "урок5/глаголыСлово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/глаголы/Слово5",
              phrase: "урок5/глаголы/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
          Существительные: [
            {
              word: "урок5/Существительные/Слово1",
              phrase: "урок5/Существительные/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/Существительные/Слово2",
              phrase: "урок5/Существительные/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/глаголы/Слово3",
              phrase: "урок5/глаголыСлово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/глаголы/Слово4",
              phrase: "урок5/глаголыСлово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/глаголы/Слово5",
              phrase: "урок5/глаголы/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
  
          Вопросы: [
            {
              word: "урок5/Вопросы/Слово1",
              phrase: "урок5/Вопросы/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/Вопросы/Слово2",
              phrase: "урок5/Вопросы/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/Вопросы/Слово3",
              phrase: "урок5/Вопросы/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/Вопросы/Слово4",
              phrase: "урок5/Вопросы/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/Вопросы/Слово5",
              phrase: "урок5/Вопросы/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
        },
        phrase: {
          "Тема фраз1": [
            {
              word: "урок5/Тема фраз1/Слово1",
              phrase: "урок5/Тема фраз1/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/Тема фраз1/Слово2",
              phrase: "урок5/Тема фраз1/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/Тема фраз1/Слово3",
              phrase: "урок5/Тема фраз1/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/Тема фраз1/Слово4",
              phrase: "урок5/Тема фраз1/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/Тема фраз1/Слово5",
              phrase: "урок5/Тема фраз1/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
          "Тема фраз2": [
            {
              word: "урок5/Тема фраз2/Слово1",
              phrase: "урок5/Тема фраз2/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/Тема фраз2/Слово2",
              phrase: "урок4/Тема фраз2/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/Тема фраз2/Слово3",
              phrase: "урок5/Тема фраз2/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/Тема фраз2/Слово4",
              phrase: "урок5/Тема фраз2/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/Тема фраз2/Слово5",
              phrase: "урок5/Тема фраз2/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
  
          "Тема фраз3": [
            {
              word: "урок5/Тема фраз3/Слово1",
              phrase: "урок5/Тема фраз3/Слово1",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/1.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/Тема фраз3/Слово2",
              phrase: "урок5/Тема фраз3/Слово2",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/2.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/Тема фраз3/Слово3",
              phrase: "урок5/Тема фраз3/Слово3",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/3.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/Тема фраз3/Слово4",
              phrase: "урок5/Тема фраз3/Слово4",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/4.mp3",
              trans: "Транскрипция",
            },
            {
              word: "урок5/Тема фраз3/Слово5",
              phrase: "урок5/Тема фраз3/Слово5",
              image: "https://f-arenda.ru/appImg/1w1.jpg",
              sound: "https://f-arenda.ru/sound/1/word/5.mp3",
              trans: "Транскрипция",
            },
          ],
        },
      },
    },
  ];
  
  
  export const USER = {
     repeat: {
        "Урок 1" : [
            { id:1,phrase:true,word:true,title: '30c',time:0},
            { id:2,phrase:true,word:true,title: '6ч',time:0},
            { id:3,phrase:true,word:true,title: '24ч',time:0},
            { id:4,phrase:false,word:false,title: '3д'},
            { id:5,phrase:false,word:false,title: '7д'},
            { id:6,phrase:false,word:false,title: '14д'},
            { id:7,phrase:false,word:false,title: '30д'},
            { id:8,phrase:false,word:false,title: '90д'},
            { id:9,phrase:false,word:false,title: '180д'},
            { id:10,phrase:false,word:false,title: '360д'}
        ],
        "Урок 2" : [  
            
        { id:1,phrase:true,word:true,title: '30c',},
        { id:2,phrase:true,word:true,title: '6ч', time: 0},
        { id:3,phrase:true,word:false,title: '24ч',time: 0},
        { id:4,phrase:false,word:false,title: '3д'},
        { id:5,phrase:false,word:false,title: '7д'},
        { id:6,phrase:false,word:false,title: '14д'},
        { id:7,phrase:false,word:false,title: '30д'},
        { id:8,phrase:false,word:false,title: '90д'},
        { id:9,phrase:false,word:false,title: '180д'},
        { id:10,phrase:false,word:false,title: '360д'}
  
        ],
        "Урок 3" : [ 
        { id:1,phrase:false,word:false,title: '30c',},
        { id:2,phrase:false,word:false,title: '6ч'},
        { id:3,phrase:false,word:false,title: '24ч'},
        { id:4,phrase:false,word:false,title: '3д'},
        { id:5,phrase:false,word:false,title: '7д'},
        { id:6,phrase:false,word:false,title: '14д'},
        { id:7,phrase:false,word:false,title: '30д'},
        { id:8,phrase:false,word:false,title: '90д'},
        { id:9,phrase:false,word:false,title: '180д'},
        { id:10,phrase:false,word:false,title: '360д'}
  
        ],
        "Урок 4" : [ 
          { id:1,phrase:false,word:false,title: '30c',},
          { id:2,phrase:false,word:false,title: '6ч'},
          { id:3,phrase:false,word:false,title: '24ч'},
          { id:4,phrase:false,word:false,title: '3д'},
          { id:5,phrase:false,word:false,title: '7д'},
          { id:6,phrase:false,word:false,title: '14д'},
          { id:7,phrase:false,word:false,title: '30д'},
          { id:8,phrase:false,word:false,title: '90д'},
          { id:9,phrase:false,word:false,title: '180д'},
          { id:10,phrase:false,word:false,title: '360д'}
      ],
        "Урок 5" : [      
        { id:1,phrase:false,word:false,title: '30c',},
        { id:2,phrase:false,word:false,title: '6ч'},
        { id:3,phrase:false,word:false,title: '24ч'},
        { id:4,phrase:false,word:false,title: '3д'},
        { id:5,phrase:false,word:false,title: '7д'},
        { id:6,phrase:false,word:false,title: '14д'},
        { id:7,phrase:false,word:false,title: '30д'},
        { id:8,phrase:false,word:false,title: '90д'},
        { id:9,phrase:false,word:false,title: '180д'},
        { id:10,phrase:false,word:false,title: '360д'}
  
        ],
  
        },
        
     point: 100,
    name: 'Diman00.'
     
  }
  